# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67fc9fcd504e096d572c5fce0f513f988aa5848794886513c4a8a84ad2c9d1bf722450fa3daa5dfbf12cb712576c91db64dc4616d94d8bdb4a10e5ba26350c92

test:
  secret_key_base: e5d0a018e8867b4259aa14a2f42eb639262fd4ec78c2c7885cff43fc224a5b9dc0993fff2f032111b1db07dcacc27b8a0127947535b2b438ea7b6a8f033f0b02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
